spring:
  application:
    name: jwechat-api-proxy
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  #redis
  redis:
    host: 192.168.0.199
    port: 6379
    password: zk900319
    timeout: 6000ms       # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 200   # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 0       # 连接池中的最小空闲连接

server:
  port: 9820

#fegin
token:
  url: http://localhost:9810

#eureka
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://yun.eqbidding.com:16000/eureka/

#weixin
weixin:
#  mp:
#    appid: wx5d57f2472e4236f1
#    secret: bd19ee0342c53bb05a8adfcc5152cae5
#    encodingaeskey: vtS3YUxauSP3ZovKj46Hj61tqDFjtQmHSIujRMOoJw0
#    token: huabaide666888
  corp:
    enabled: true
    corpid: ww4b055f3bec10790d
    oa-clock-in-agent-id: 3010011   #默认打卡应用AgentId
    oa-approve-agent-id: 3010040   #默认审批应用AgentId
    secrets: {1000004: 'flxH-98wCRjlFe1Ncp5iEIJzuOBsEyShx7Oe5txJx8A', 1000005: '8UPp5StJN1ena2yHF3vBtSfzJZEJr33_EpDHO8PFBps',3010011: 'WC7tb-01bvIkFTXf39Xqy2ZxfnLblnaMh2UBZHcck7Y',3010040: 'PLrTgmHyLzkMlh_wFGf4mqpzqvCWSBXp2U1GA0kK1I0'}