spring:
  application:
    name: jwechat-api-proxy
  #redis
  redis:
#    host: 192.168.1.199
    host: localhost
    port: 6379
    password: zk900319
    timeout: 6000ms       # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 200   # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 0       # 连接池中的最小空闲连接

server:
  port: 9820

#fegin
token:
  url: http://localhost:9810

weixin:
#  mp:
#    appid: wx5d57f2472e4236f1
#    secret: bd19ee0342c53bb05a8adfcc5152cae5
#    encodingaeskey: vtS3YUxauSP3ZovKj46Hj61tqDFjtQmHSIujRMOoJw0
#    token: huabaide666888
  corp:
    enabled: true
    corpid: ww4b055f3bec10790d
    secrets: {1000004: 'flxH-98wCRjlFe1Ncp5iEIJzuOBsEyShx7Oe5txJx8A', 1000005: '8UPp5StJN1ena2yHF3vBtSfzJZEJr33_EpDHO8PFBps'}